### PR TITLE
Small typo / markdown syntax fixes

### PR DESCRIPTION
**Pull request by atdt**

### CODE REVIEW

**Comment by dcwalk** [comment]
These look great! One question for @titaniumbones tho-- this material was merged into https://github.com/datarefugephilly/workflow/tree/master/harvesting-toolkit. Could we depreciate (aka delete?) this repo and bring these changes in over there?

**Comment by titaniumbones** [comment]
Yes, we should. Foolish if me not to have some earlier. We need to also update overview I guess. Will tune in when I m sitting down...

On January 23, 2017 9:26:13 AM EST, dcwalk <notifications@github.com> wrote:
>These look great! One question for @titaniumbones tho-- this material
>was merged into
>https://github.com/datarefugephilly/workflow/tree/master/harvesting-toolkit.
>Could we depreciate (aka delete?) this repo and bring these changes in
>over there?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/harvesting-toolkit/pull/16#issuecomment-274500974

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by dcwalk** [comment]
@atdt-- I'm going to move your PR changes (manually) to the other repo which has everything https://github.com/datarefugephilly/workflow/. Sorry for any confusion!

**Comment by dcwalk** [comment]
Closing this as the content of this PR is now here: https://github.com/datarefugephilly/workflow/pull/8

**Pull request closed without merging**
